package de.immoPiraten.ImmoScout24;

public enum ConditionType {
	FIRST_TIME_USE,
	FIRST_TIME_USE_AFTER_REFURBISHMENT,
	MINT_CONDITION,
	REFURBISHED,
	MODERNIZED,
	FULLY_RENOVATED,
	WELL_KEPT,
	NEED_OF_RENOVATION,
	NEGOTIABLE,
	RIPE_FOR_DEMOLITION;
}
