package de.immoPiraten.ImmoScout24;

public enum HeatingType {
	NO_INFORMATION,
	SELF_CONTAINED_CENTRAL_HEATING,
	STOVE_HEATING,
	CENTRAL_HEATING,
	COMBINED_HEAT_AND_POWER_PLANT,
	ELECTRIC_HEATING,
	DISTRICT_HEATING,
	FLOOR_HEATING,
	GAS_HEATING,
	WOOD_PELLET_HEATING,
	NIGHT_STORAGE_HEATER,
	OIL_HEATING,
	SOLAR_HEATING,
	HEAT_PUMP;
}