package de.immoPiraten.ImmoScout24;

public enum ResidentialRealEstateType {
	NO_INFORMATION,
	SINGLE_FAMILY_HOUSE,
	MID_TERRACE_HOUSE,
	END_TERRACE_HOUSE,
	MULTI_FAMILY_HOUSE,
	BUNGALOW,
	FARMHOUSE,
	SEMIDETACHED_HOUSE,
	VILLA,
	CASTLE_MANOR_HOUSE,
	SPECIAL_REAL_ESTATE,
	ROOF_STOREY,
	LOFT,
	MAISONETTE,
	PENTHOUSE,
	TERRACED_FLAT,
	GROUND_FLOOR,
	APARTMENT,
	RAISED_GROUND_FLOOR,
	HALF_BASEMENT,
	OTHER;
}